### PR TITLE
Specify Carbon version for 1.0.0

### PR DESCRIPTION
**Pull request by poraghal**

### CODE REVIEW

**Comment by poraghal** [comment]
@grahamharper 

Updated the Carbon versions, see:

https://github.com/IBM/spm-ui-addon-devenv/pull/23

I'm off next week, so make any mods required and push out pls

**Comment by poraghal** [comment]
Thanks Graham, was just about to look at the errors, much appreciated.

**Comment by grahamharper** [comment]
@poraghal if you're using VS Code, I'd recommend installing [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) which automatically formats your code on save.

**Comment by poraghal** [comment]
@poraghal I can't get a local build in VSC going from the code base, so just did it online, backfired, huh ;-)

**Pull request merged**
